# Generated by Django 6.0.8 on 2026-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('microtask', 'Microtask'), ('data_entry', 'Data Entry'), ('transcription', 'Transcription'), ('data_labeling', 'Data Labeling'), ('ai_evaluation', 'AI Evaluation'), ('research', 'Research'), ('testing', 'Testing'), ('content_creation', 'Content Creation'), ('freelance', 'Freelance Project')], max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('base_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deadline_hours', models.IntegerField(default=72)),
                ('min_level_required', models.IntegerField(default=1)),
                ('required_specializations', models.JSONField(blank=True, default=list)),
                ('auto_generate', models.BooleanField(default=False)),
                ('generate_frequency_hours', models.IntegerField(default=24)),
                ('max_active_tasks', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
