# Generated by Django 6.0.8 on 2026-08-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('mobile_development', 'Mobile Development'), ('ai_ml', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('devops', 'DevOps')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.IntegerField()),
                ('number_of_lessons', models.IntegerField(default=10)),
                ('min_level_required', models.IntegerField(default=1)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('auto_generate', models.BooleanField(default=False)),
                ('generate_frequency_hours', models.IntegerField(default=168)),
                ('max_active_courses', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
