# Generated by Django 6.0.8 on 2026-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupgradepayment',
            name='payment_type',
            field=models.CharField(choices=[('activation', 'Activation'), ('upgrade', 'Level Upgrade')], default='upgrade', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
