# Generated by Django 6.0.8 on 2026-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('rating', 'Rating'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('number', 'Number')], max_length=20)),
                ('category', models.CharField(choices=[('market_research', 'Market Research'), ('product_feedback', 'Product Feedback'), ('customer_satisfaction', 'Customer Satisfaction'), ('academic', 'Academic'), ('opinion', 'Opinion'), ('lifestyle', 'Lifestyle')], max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('market_research', 'Market Research'), ('product_feedback', 'Product Feedback'), ('customer_satisfaction', 'Customer Satisfaction'), ('academic', 'Academic'), ('opinion', 'Opinion'), ('lifestyle', 'Lifestyle')], max_length=50)),
                ('description', models.TextField()),
                ('base_reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time_minutes', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('auto_generate', models.BooleanField(default=False)),
                ('generate_frequency_hours', models.IntegerField(default=24)),
                ('max_active_surveys', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
