# Generated by Django 6.0.8 on 2026-08-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('surveys', '0001_initial'),
        ('tasks', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='earning',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.surveyresponse'),
        ),
        migrations.AddField(
            model_name='earning',
            name='task_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasksubmission'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='survey_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.surveyresponse'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='task_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasksubmission'),
        ),
    ]
